name: Create windows .exe file

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install --upgrade pip; pip install -r requirements.txt
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Pokemon Card Price Checker'
          options: --onefile, --name "Pokemon Card Price Checker", --console,